apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: rds-secret-provider
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "RdsUserSecret"
        objectType: "secretsmanager"
        objectAlias: "user-secret"
      - objectName: "RdsMasterSecret"
        objectType: "secretsmanager"
        objectAlias: "master-secret"
